### ISSUE TITLE
When will the training code be available?

### ISSUE THREAD

**Issue by zhengthomastang** [krrish94/stacked-hourglass#1]
Thanks for your great work, which really inspired me on my research. 

As mentioned in the ReadMe.md, the training code for car keypoint localization will be updated. When will that be available? Will the original training code of [pose-hg-train](https://github.com/princeton-vl/pose-hg-train) work for this task? 

Also, is it possible to share the training set you used? We would like to expand the training set and make it work on more diverse car types. 

Finally, it looks like the [provided pre-trained model](https://www.dropbox.com/s/v4f770ebdenia0g/hg-binary-trained-singleGPU.t7?dl=0) is not compatible with the [CarKeypoints](https://github.com/krrish94/CarKeypoints) project. Do I need to use a different version of training/testing code for that?

**Comment by krrish94** [comment]
Hi!

As for the [CarKeypoints](https://github.com/krrish94/CarKeypoints) repo, the pretrained model is [here](https://www.dropbox.com/s/qezt3e02j4uawov/model.t7?dl=0) as mentioned in the `README`.

And, we sensed that not a lot of people still use Torch these days; PyTorch or TensorFlow seem to be the framework of choice, so we never really got to a release. There are a few PyTorch/TensorFlow repos out there that have an implementation of the stacked hourglass network.

However, if you still need our training code, which is in Lua Torch, feel free to DM me; I'll be happy to share.
