### ISSUE TITLE
car vs. human pose

### ISSUE THREAD

**Issue by soldierofhell** [krrish94/stacked-hourglass#2]
Hi @krrish94,
Were there any important differences in training car keypoints in contrast to human pose? Probably slightly different flip augmentation, anything else?
For example I'm wondering what is the accuracy in properly recognized left/right and front/rear elements and are there any tricks to improve it?

Regards,

**Comment by krrish94** [comment]
If you look through the code, you'll realize that we've modified a few convolutional layers before the first hourglass module. Empirically, we found that a combination of this modified architecture, and a data augmentation strategy based on horizontal flips and random crops was sufficient to train a good car keypoint localization network. If you look at some of our other work, you'll realize that adding synthetic (rendered) training data presents a significant boost in accuracy. You might also find this paper relevant: https://arxiv.org/pdf/1801.03399.pdf
